/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#c7f02d',
        'on-primary': '#121409',
        secondary: '#d6a9ff',
        'secondary-surface': '#383a2d',
        tertiary: '#ffb4ab',
        pink: '#ffb7e9',
        lavender: '#C9C0E6',
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-surface-alt': 'var(--color-on-surface-alt)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        error: '#ffb4ab',
        background: 'var(--color-background)',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '12px',
        xl: '24px',
        '2xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '260px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'stack-lg': '32px',
        'stack-xs': '4px',
        'container-max': '1440px',
        'gutter': '24px',
      },
      fontFamily: {
        display: ['Space Grotesk', 'sans-serif'],
        body: ['Space Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        display: ['64px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '800' }],
        h1: ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'h1-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'mono-sm': ['13px', { lineHeight: '1.5', fontWeight: '450' }],
      },
      boxShadow: {
        brutal: '4px 4px 0px 0px rgba(0,0,0,1)',
        'brutal-lg': '8px 8px 0px 0px rgba(0,0,0,1)',
        'brutal-xl': '12px 12px 0px 0px rgba(0,0,0,1)',
        'brutal-sm': '2px 2px 0px 0px rgba(0,0,0,1)',
      },
      animation: {
        'grid-scroll': 'grid-scroll 20s linear infinite',
        'blob-float': 'blob-float 15s ease-in-out infinite alternate',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'spin-slow': 'spin 60s linear infinite',
      },
      keyframes: {
        'grid-scroll': {
          '0%': { backgroundPosition: '0 0' },
          '100%': { backgroundPosition: '40px 40px' },
        },
        'blob-float': {
          '0%': { transform: 'translate(-10%, -10%) scale(1)' },
          '100%': { transform: 'translate(10%, 10%) scale(1.2)' },
        },
      },
    },
  },
  plugins: [],
};
